[package]
name = "lib_miner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.6"
rand_pcg = "0.3.1"
rand = "0.8.5"
serde = "1.0.150"
serde_json = "1.0.89"
